// import { Schema } from "mongoose";

export type IReviews = {
  rating: number;
  comment: string;
  // userID: Schema.Types.ObjectId;
  reviewedBy: string;
};

export type IKeyFeatures = {
  brand: string;
  model: string;
  specification?: string;
  port?: string;
  type?: string;
  resolution?: string;
  voltage?: string;
  clockSpeed?: string;
  cache?: string;
  cores?: string;
  socket?: string;
  threads?: string;
  baseFrequency?: string;
  maximumTurboFrequency?: string;
  TDP?: string;
  fanSpeed?: string;
  fanAirflow?: string;
  noise?: string;
  airPressure?: string;
  connector?: string;
  dimension: string;
  weight?: string;
  supported?: string;
  supportedCPU?: string;
  chipset?: string;
  BIOS?: string;
  formFactor?: string;
  audio?: string;
  slots?: string;
  supportedMemory?: string;
  supportedStorage?: string;
  maximumMemory?: string;
  graphics?: string;
  maxSharedMemory?: string;
  specialFeatures?: string;
  USB?: string;
  HDMI?: string;
  capacity?: string;
  frequency?: string;
  latency?: string;
  pin?: string;
  continuousPower?: string;
  efficiency?: string;
  others?: string;
  modularType?: string;
  current?: string;
  fanSize?: string;
  CPU?: string;
  floppy?: string;
  PCI?: string;
  mainPower?: string;
  displaySize?: string;
  displayType?: string;
  panelType?: string;
  pixelPitch?: string;
  aspectRatio?: string;
  viewingAngle?: string;
  brightness?: string;
  refreshRate?: string;
  colorSupport?: string;
  responseTime?: string;
  speaker?: string;
  VGA?: string;
  color?: string;
  powerConsumption?: string;
};

export type IComponent = {
  image: string;
  name: string;
  category: string;
  status: "In Stock" | "Out of Stock";
  price: string;
  description: string;
  warranty: number;
  reviews?: IReviews[];
  KeyFeatures: IKeyFeatures;
};
